name: .NET

# The point here is to always check format and tests on every push
# and also on PRs to main or production, without double triggering
# after acepting the PR

on:
  push:
    branches:
    - '**'
    - '!main'
    - '!production'
    
  pull_request:
    branches:
    - main
    - production

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Install dotnet format
      run: dotnet tool update --global dotnet-format
    - name: Run dotnet format
      run: dotnet-format --check --verbosity diagnostic
    - name: Test
      run: dotnet test --no-build --verbosity normal
